### ISSUE TITLE
Launcher: initial setup fails if path contains spaces

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#278]
I unzipped the launcher to a path with spaces: `C:\Users\Christopher\Downloads\otree-launcher-master (5)\otree-launcher-master\otree_launcher\`

I got the below error. I removed the space from my path and re-ran, and it installed correctly.

Don't know if Windows specific.

```
 The oTree Launcher says 'Hello'
> Creating virtualenv in 'C:\Users\Christopher\AppData\Roaming\otree-launcher\venv'...
> Downloading requirements file...
> Creating virtualenv install script...
> Creating venv, please wait (this may take a few minutes)...
> New python executable in C:\Users\Christopher\AppData\Roaming\otree-launcher\venv\Scripts\python.exe
> Installing setuptools, pip...
> 
>   Complete output from command C:\Users\Christopher...v\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
>   Ignoring indexes: https://pypi.python.org/simple
> Collecting setuptools
>   This repository located at None is not a trusted host, if this repository is available via HTTPS it is recommend to use HTTPS instead, otherwise you may silence this warning with '--trusted-host None'.
>   DEPRECATION: Implicitly allowing locations which are not hosted at a secure origin is deprecated and will require the use of --trusted-host in the future.
>   This repository located at None is not a trusted host, if this repository is available via HTTPS it is recommend to use HTTPS instead, otherwise you may silence this warning with '--trusted-host None'.
>   This repository located at None is not a trusted host, if this repository is available via HTTPS it is recommend to use HTTPS instead, otherwise you may silence this warning with '--trusted-host None'.
>   Exception:
>   Traceback (most recent call last):
>     File "C:\Users\Christopher\Downloads\otree-launcher-master (5)\otree-launcher-master\otree_launcher\libs\virtualenv\virtualenv_support\pip-6.0.6-py2.py3-none-any.whl\pip\basecommand.py", line 232, in main
>       status = self.run(options, args)
>     File "C:\Users\Christopher\Downloads\otree-launcher-master (5)\otree-launcher-master\otree_launcher\libs\virtualenv\virtualenv_support\pip-6.0.6-py2.py3-none-any.whl\pip\commands\install.py", line 339, in run
> Initial setup complete.
Click on the 'Deploys' menu to create a new deploy.
>       requirement_set.prepare_files(finder)
>     File "C:\Users\Christopher\Downloads\otree-launcher-master (5)\otree-launcher-master\otree_launcher\libs\virtualenv\virtualenv_support\pip-6.0.6-py2.py3-none-any.whl\pip\req\req_set.py", line 333, in prepare_files
>       upgrade=self.upgrade,
>     File "C:\Users\Christopher\Downloads\otree-launcher-master (5)\otree-launcher-master\otree_launcher\libs\virtualenv\virtualenv_support\pip-6.0.6-py2.py3-none-any.whl\pip\index.py", line 351, in find_requirement
>       for page in self._get_pages(locations, req):
>     File "C:\Users\Christopher\Downloads\otree-launcher-master (5)\otree-launcher-master\otree_launcher\libs\virtualenv\virtualenv_support\pip-6.0.6-py2.py3-none-any.whl\pip\index.py", line 566, in _get_pages
>       page = self._get_page(location, req)
>     File "C:\Users\Christopher\Downloads\otree-launcher-master (5)\otree-launcher-master\otree_launcher\libs\virtualenv\virtualenv_support\pip-6.0.6-py2.py3-none-any.whl\pip\index.py", line 783, in _get_page
>       return HTMLPage.get_page(link, req, session=self.session)
>     File "C:\Users\Christopher\Downloads\otree-launcher-master (5)\otree-launcher-master\otree_launcher\libs\virtualenv\virtualenv_support\pip-6.0.6-py2.py3-none-any.whl\pip\index.py", line 872, in get_page
>       "Cache-Control": "max-age=600",
>     File "C:\Users\Christopher\Downloads\otree-launcher-master (5)\otree-launcher-master\otree_launcher\libs\virtualenv\virtualenv_support\pip-6.0.6-py2.py3-none-any.whl\pip\_vendor\requests\sessions.py", line 473, in get
>       return self.request('GET', url, **kwargs)
>     File "C:\Users\Christopher\Downloads\otree-launcher-master (5)\otree-launcher-master\otree_launcher\libs\virtualenv\virtualenv_support\pip-6.0.6-py2.py3-none-any.whl\pip\download.py", line 365, in request
>       return super(PipSession, self).request(method, url, *args, **kwargs)
>     File "C:\Users\Christopher\Downloads\otree-launcher-master (5)\otree-launcher-master\otree_launcher\libs\virtualenv\virtualenv_support\pip-6.0.6-py2.py3-none-any.whl\pip\_vendor\requests\sessions.py", line 447, in request
>       prep = self.prepare_request(req)
>     File "C:\Users\Christopher\Downloads\otree-launcher-master (5)\otree-launcher-master\otree_launcher\libs\virtualenv\virtualenv_support\pip-6.0.6-py2.py3-none-any.whl\pip\_vendor\requests\sessions.py", line 378, in prepare_request
>       hooks=merge_hooks(request.hooks, self.hooks),
>     File "C:\Users\Christopher\Downloads\otree-launcher-master (5)\otree-launcher-master\otree_launcher\libs\virtualenv\virtualenv_support\pip-6.0.6-py2.py3-none-any.whl\pip\_vendor\requests\models.py", line 304, in prepare
>       self.prepare_url(url, params)
>     File "C:\Users\Christopher\Downloads\otree-launcher-master (5)\otree-launcher-master\otree_launcher\libs\virtualenv\virtualenv_support\pip-6.0.6-py2.py3-none-any.whl\pip\_vendor\requests\models.py", line 358, in prepare_url
>       "Perhaps you meant http://{0}?".format(url))
>   MissingSchema: Invalid URL u'(5)\\otree-launcher-master\\otree_launcher\\libs\\virtualenv': No schema supplied. Perhaps you meant http://(5)\otree-launcher-master\otree_launcher\libs\virtualenv?
> 
> ----------------------------------------
> ...Installing setuptools, pip...done.
> Traceback (most recent call last):
>   File "otree_launcher\libs\virtualenv\virtualenv.py", line 2352, in <module>
>     main()
>   File "otree_launcher\libs\virtualenv\virtualenv.py", line 825, in main
>     symlink=options.symlink)
>   File "otree_launcher\libs\virtualenv\virtualenv.py", line 993, in create_environment
>     install_wheel(to_install, py_executable, search_dirs)
>   File "otree_launcher\libs\virtualenv\virtualenv.py", line 961, in install_wheel
>     'PIP_NO_INDEX': '1'
>   File "otree_launcher\libs\virtualenv\virtualenv.py", line 903, in call_subprocess
>     % (cmd_desc, proc.returncode))
> OSError: Command C:\Users\Christopher...v\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 2
```

**Comment by leliel12** [comment]
this issue is really hard to fix, because is a PIP windows bug https://github.com/pypa/pip/issues/1504

**Comment by leliel12** [comment]
i tryng to move the virtualenv code to a windows/Temp directory.. and thas must be work

**Comment by leliel12** [comment]
this probably go to "whot fix status" but one more try

**Comment by leliel12** [comment]
well the solution was simple at the end. From now otree-launcher will not run if it inside a path with spaces. At the end is a limitation of python itself

**Comment by oTree-org** [comment]
The launcher now works for me even if there are spaces in the path, nice.

**Comment by leliel12** [comment]
This is because your directory has more thn 8 chars and they be compresses
into something like SOMETH~1. and also the space is after the 6 character.



2015-04-30 9:50 GMT-03:00 oTree-org <notifications@github.com>:

> The launcher now works for me even if there are spaces in the path, nice.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oTree-org/otree-core/issues/278#issuecomment-97762157>
> .
>



-- 
Juan B Cabral
