### ISSUE TITLE
./otree celery worker => AppRegistryNotReady: Models aren't loaded yet.

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#311]
I am trying to get the timeout feature working so that page timeouts work even if the user closes their browser. However, this requires celery, which is not working yet.

Repro steps:

* Checkout `timeout` branch of oTree library and core
* `resetdb` & `runserver
* In a separate terminal, do `./otree celery worker`
* Play the Trust game

Here is the error:

```
[2015-04-24 00:08:19,211: WARNING/Worker-1] C:\oTree\venv\lib\site-packages\celery\app\trace.py:365: RuntimeWarning: Exc
eption raised outside body: AppRegistryNotReady("Models aren't loaded yet.",):
Traceback (most recent call last):
  File "C:\oTree\venv\lib\site-packages\celery\app\trace.py", line 253, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "C:\oTree\venv\lib\site-packages\celery\app\trace.py", line 201, in on_error
    R = I.handle_error_state(task, eager=eager)
  File "C:\oTree\venv\lib\site-packages\celery\app\trace.py", line 85, in handle_error_state
    }[self.state](task, store_errors=store_errors)
  File "C:\oTree\venv\lib\site-packages\celery\app\trace.py", line 118, in handle_failure
    req.id, exc, einfo.traceback, request=req,
  File "C:\oTree\venv\lib\site-packages\celery\backends\base.py", line 121, in mark_as_failure
    traceback=traceback, request=request)
  File "C:\oTree\venv\lib\site-packages\celery\backends\base.py", line 256, in store_result
    request=request, **kwargs)
  File "C:\oTree\venv\lib\site-packages\djcelery\backends\database.py", line 29, in _store_result
    traceback=traceback, children=self.current_task_children(request),
  File "C:\oTree\venv\lib\site-packages\djcelery\managers.py", line 42, in _inner
    return fun(*args, **kwargs)
  File "C:\oTree\venv\lib\site-packages\djcelery\managers.py", line 181, in store_result
    'meta': {'children': children}})
  File "C:\oTree\venv\lib\site-packages\djcelery\managers.py", line 87, in update_or_create
    return get_queryset(self).update_or_create(**kwargs)
  File "C:\oTree\venv\lib\site-packages\djcelery\managers.py", line 70, in update_or_create
    obj, created = self.get_or_create(**kwargs)
  File "C:\oTree\venv\lib\site-packages\django-1.7.7-py2.7.egg\django\db\models\query.py", line 422, in get_or_create
    return self.get(**lookup), False
  File "C:\oTree\venv\lib\site-packages\django-1.7.7-py2.7.egg\django\db\models\query.py", line 345, in get
    clone = self.filter(*args, **kwargs)
  File "C:\oTree\venv\lib\site-packages\django-1.7.7-py2.7.egg\django\db\models\query.py", line 691, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\oTree\venv\lib\site-packages\django-1.7.7-py2.7.egg\django\db\models\query.py", line 709, in _filter_or_exclu
de
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\oTree\venv\lib\site-packages\django-1.7.7-py2.7.egg\django\db\models\sql\query.py", line 1331, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "C:\oTree\venv\lib\site-packages\django-1.7.7-py2.7.egg\django\db\models\sql\query.py", line 1358, in _add_q
    current_negated=current_negated, connector=connector)
  File "C:\oTree\venv\lib\site-packages\django-1.7.7-py2.7.egg\django\db\models\sql\query.py", line 1182, in build_filte
r
    lookups, parts, reffed_aggregate = self.solve_lookup_type(arg)
  File "C:\oTree\venv\lib\site-packages\django-1.7.7-py2.7.egg\django\db\models\sql\query.py", line 1120, in solve_looku
p_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\oTree\venv\lib\site-packages\django-1.7.7-py2.7.egg\django\db\models\sql\query.py", line 1383, in names_to_pa
th
    field, model, direct, m2m = opts.get_field_by_name(name)
  File "C:\oTree\venv\lib\site-packages\django-1.7.7-py2.7.egg\django\db\models\options.py", line 416, in get_field_by_n
ame
    cache = self.init_name_map()
  File "C:\oTree\venv\lib\site-packages\django-1.7.7-py2.7.egg\django\db\models\options.py", line 445, in init_name_map
    for f, model in self.get_all_related_m2m_objects_with_model():
  File "C:\oTree\venv\lib\site-packages\django-1.7.7-py2.7.egg\django\db\models\options.py", line 563, in get_all_relate
d_m2m_objects_with_model
    cache = self._fill_related_many_to_many_cache()
  File "C:\oTree\venv\lib\site-packages\django-1.7.7-py2.7.egg\django\db\models\options.py", line 577, in _fill_related_
many_to_many_cache
    for klass in self.apps.get_models():
  File "C:\oTree\venv\lib\site-packages\django-1.7.7-py2.7.egg\django\utils\lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "C:\oTree\venv\lib\site-packages\django-1.7.7-py2.7.egg\django\apps\registry.py", line 168, in get_models
    self.check_models_ready()
  File "C:\oTree\venv\lib\site-packages\django-1.7.7-py2.7.egg\django\apps\registry.py", line 131, in check_models_ready

    raise AppRegistryNotReady("Models aren't loaded yet.")
AppRegistryNotReady: Models aren't loaded yet.
```

**Comment by gregmuellegger** [comment]
This was quite tricky to analyze since the error didn't give much detail about what really caused the error. I found that the error came from the fact that we are using the celery's database backend to store task data. So celery tried to access the database when django's setup wasn't yet ready. I assume that this is weird bug from a combination of using celery, django-celery and Django 1.7.

I think I resolved the issue in the `timeout` branch by using a different method of setting up celery inside the project. The confusing thing here is that django-celery has a different guide on how to setup celery with django than the celery itself has. So there are two different tutorials in the wild. A legacy method of doing this (django-celery documentaion) and a newer one (from the celery documentation).

When I first set celery up for otree, I tried the one from the celery docs which didn't work. So I sticked to the django-celery one. Now I resolved the issue from this ticket by removing the bits from the otree code that the django-celery docs described and replaced them with a setup from the celery docs. And now it seems to work ... Either the latest versions of celery and django-celery fixed a bug that made the new method of setting things up work, or I did something differently in the first try.

However you need to update the `timeout` branches of oTree-lib and otree-core and start celery now with:
`./otree celery worker -A celeryapp:app`
Then:
`./otree runserver`

And test if it works. Once you can verify that this is resolved, we can make a shortcut for the celery command to just read `./otree runtaskqueue` or similar for easier usage.
