### ISSUE TITLE
Metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#318]
In the [id-map](https://github.com/oTree-org/otree-core/tree/id-map) branch I am incorporating the [django-idmap](https://pypi.python.org/pypi/django-idmap) library to resolve some issues related to duplicate model instances. Everything works during prototyping except now I'm trying to make `SharedMemoryModel` the base model for all oTree models in https://github.com/oTree-org/otree-core/blob/id-map/otree/db/models.py: 

```
class OTreeModel(SharedMemoryModel):
    __metaclass__ = OTreeModelBase

    class Meta:
        abstract = True
```

However, I get the below error. Hoping someone can help refactor to resolve this.

```
Traceback (most recent call last):
  File "runtests.py", line 31, in <module>
    runtests(*sys.argv[1:])
  File "runtests.py", line 21, in runtests
    django.setup()
  File "C:\oTree\venv\lib\site-packages\django-1.7.7-py2.7.egg\django\__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\oTree\venv\lib\site-packages\django-1.7.7-py2.7.egg\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\oTree\venv\lib\site-packages\django-1.7.7-py2.7.egg\django\apps\config.py", line 116, in create
    mod = import_module(mod_path)
  File "C:\Python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\oTree\core\otree\apps.py", line 12, in <module>
    from otree.models.session import StubModel, GlobalSingleton
  File "C:\oTree\core\otree\models\__init__.py", line 6, in <module>
    from otree.db import models
  File "C:\oTree\core\otree\db\models.py", line 45, in <module>
    class OTreeModel(SharedMemoryModel):
  File "C:\oTree\core\otree\db\models.py", line 23, in __new__
    new_class = super(OTreeModelBase, cls).__new__(cls, name, bases, attrs)
  File "C:\oTree\venv\lib\site-packages\django-1.7.7-py2.7.egg\django\db\models\base.py", line 72, in __new__
    new_class = super_new(cls, name, bases, {'__module__': module})
TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

**Comment by gregmuellegger** [comment]
Should be fixed with the latest commit in the id-map branch.
The tests are passing :)
