### ISSUE TITLE
otree.common is not import friendly

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-core#338]
Hi,

I don't know if this is a bug.

I wanted to to get familiar with `json_safe`.  However, when I try to load something from `otree.common`, I'm told to set the currency code first.  Can't it just take some standard value by default?  I use vanilla `python2` with `virualenv`.

```
>>> from otree.common import safe_json
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rasmus/src/uni-src/eui-papers/asset-experiment/otree/env/lib/python2.7/site-packages/otree/common.py", line 10, in <module>
    import easymoney
  File "/home/rasmus/src/uni-src/eui-papers/asset-experiment/otree/env/lib/python2.7/site-packages/easymoney.py", line 16, in <module>
    class Money(Decimal):
  File "/home/rasmus/src/uni-src/eui-papers/asset-experiment/otree/env/lib/python2.7/site-packages/easymoney.py", line 18, in Money
    CODE = getattr(settings, 'CURRENCY_CODE', 'USD')
  File "/home/rasmus/src/uni-src/eui-papers/asset-experiment/otree/env/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/home/rasmus/src/uni-src/eui-papers/asset-experiment/otree/env/lib/python2.7/site-packages/django/conf/__init__.py", line 40, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting CURRENCY_CODE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

**Comment by leliel12** [comment]
You can't import a djando project i side a vanilla python session. This
can't be fixed

If you want to run a shell use

python otree shell

Juan BC (sent from my phone)

**Comment by pank** [comment]
I see.  I had no idea.  But that's a great tip.
