### ISSUE TITLE
Travis/PyPI: "No local packages or download links found for honcho>=0.6.6"

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#349]
We just added the "honcho" package as a dependency for otree-core.

Locally, I can do  "pip install honcho >= 0.6.6", but this doesn't work on Travis.
I got this error multiple times:

https://travis-ci.org/oTree-org/otree-core/builds/69237336#L1003

I wonder if the problem only occurs on Travis, or other platforms also.

**Comment by oTree-org** [comment]
If I install otree-core locally with `python setup.py develop`, I get this same honcho error:

```
[...]
Searching for honcho>=0.6.6
Reading https://pypi.python.org/simple/honcho/
No local packages or download links found for honcho>=0.6.6
error: Could not find suitable distribution for Requirement.parse('honcho>=0.6.6')
```

But if I install it with Pip, it works fine:

```
C:\oTree\core [master]> pip install honcho>=0.6.6
Downloading/unpacking honcho>=0.6.6
  Downloading honcho-0.6.6-py2.py3-none-any.whl
Downloading/unpacking colorama (from honcho>=0.6.6)
  Downloading colorama-0.3.3.tar.gz
  Running setup.py (path:C:\oTree\venv\build\colorama\setup.py) egg_info for package colorama

Installing collected packages: honcho, colorama
  Running setup.py install for colorama

Successfully installed honcho colorama
Cleaning up...
C:\oTree\core [master]>
```

**Comment by leliel12** [comment]
This is related to argparse version. Some versions otree-core is not found on mac

**Comment by pank** [comment]
FWIW, I got this problem when I tried to update `otree` via `pip` on my Debian server.

When I try to install it manually, I get

```
Downloading/unpacking honcho==0.6.6

  Getting page http://pypi.python.org/simple/honcho
  URLs to search for versions for honcho==0.6.6:
  * http://pypi.python.org/simple/honcho/0.6.6
  * http://pypi.python.org/simple/honcho/
  Getting page http://pypi.python.org/simple/honcho/0.6.6
  Getting page http://pypi.python.org/simple/honcho/
  Could not fetch URL http://pypi.python.org/simple/honcho/0.6.6: HTTP Error 404: Not Found
  Will skip URL http://pypi.python.org/simple/honcho/0.6.6 when looking for download links for honcho==0.6.6
  Analyzing links from page https://pypi.python.org/simple/honcho/
    Skipping link https://pypi.python.org/packages/2.7/h/honcho/honcho-0.6.0-py2-none-any.whl#md5=2492810037b77cc39b3fdd9bf73edc31 (from https://pypi.python.org/simple/honcho/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/2.7/h/honcho/honcho-0.6.1-py2.py3-none-any.whl#md5=4c5cebd5b1525f2c02402f47dd89eb72 (from https://pypi.python.org/simple/honcho/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/2.7/h/honcho/honcho-0.6.2-py2.py3-none-any.whl#md5=ff0398999fe55d8ba7d41be520e39519 (from https://pypi.python.org/simple/honcho/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/2.7/h/honcho/honcho-0.6.3-py2.py3-none-any.whl#md5=4f7db6c48a8b6c5ea4e80fd31032756c (from https://pypi.python.org/simple/honcho/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/2.7/h/honcho/honcho-0.6.4-py2.py3-none-any.whl#md5=4deb6ae859ab78753204a46a7b515e70 (from https://pypi.python.org/simple/honcho/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/2.7/h/honcho/honcho-0.6.5-py2.py3-none-any.whl#md5=e84e53e89427ddf204fd51db0d589288 (from https://pypi.python.org/simple/honcho/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/2.7/h/honcho/honcho-0.6.6-py2.py3-none-any.whl#md5=b8568cbc456167e21210857739cf77b1 (from https://pypi.python.org/simple/honcho/); unknown archive format: .whl
    Found link https://pypi.python.org/packages/source/h/honcho/honcho-0.0.1.tar.gz#md5=2c982b087a384a15f47626c1c5adf4c9 (from https://pypi.python.org/simple/honcho/), version: 0.0.1
    Found link https://pypi.python.org/packages/source/h/honcho/honcho-0.0.2.tar.gz#md5=c96100017a49db028ceb7cd2bc8dc175 (from https://pypi.python.org/simple/honcho/), version: 0.0.2
    Found link https://pypi.python.org/packages/source/h/honcho/honcho-0.0.3.tar.gz#md5=ca6826f82e9f8ee54d27ccbc52486f95 (from https://pypi.python.org/simple/honcho/), version: 0.0.3
    Found link https://pypi.python.org/packages/source/h/honcho/honcho-0.0.4.tar.gz#md5=3b4d2d7f9f315005fc70bae5844a2cd5 (from https://pypi.python.org/simple/honcho/), version: 0.0.4
    Found link https://pypi.python.org/packages/source/h/honcho/honcho-0.1.0.tar.gz#md5=2b08188daa30f7a065ed3709f8fd76a3 (from https://pypi.python.org/simple/honcho/), version: 0.1.0
    Found link https://pypi.python.org/packages/source/h/honcho/honcho-0.2.0.tar.gz#md5=3e81add102bf61f239945be655b678ec (from https://pypi.python.org/simple/honcho/), version: 0.2.0
    Found link https://pypi.python.org/packages/source/h/honcho/honcho-0.3.1.tar.gz#md5=16c55160a4ce8c1e194392caf1b053fa (from https://pypi.python.org/simple/honcho/), version: 0.3.1
    Found link https://pypi.python.org/packages/source/h/honcho/honcho-0.4.0.tar.gz#md5=8a9ea3aeacc7351d19fe948beb6e9737 (from https://pypi.python.org/simple/honcho/), version: 0.4.0
    Found link https://pypi.python.org/packages/source/h/honcho/honcho-0.4.1.tar.gz#md5=9007734c3ba5c7d3b3eda4b28329c58c (from https://pypi.python.org/simple/honcho/), version: 0.4.1
    Found link https://pypi.python.org/packages/source/h/honcho/honcho-0.4.2.tar.gz#md5=16d8269c975c38621feba75645c1f85d (from https://pypi.python.org/simple/honcho/), version: 0.4.2
    Found link https://pypi.python.org/packages/source/h/honcho/honcho-0.5.0.tar.gz#md5=b93651497472baf86c4ddf84bec1467b (from https://pypi.python.org/simple/honcho/), version: 0.5.0
    Skipping link http://ddollar.github.com/foreman (from https://pypi.python.org/simple/honcho/); not a file
    Skipping link http://ddollar.github.com/foreman/ (from https://pypi.python.org/simple/honcho/); not a file
    Skipping link http://docs.python.org/library/queue.html (from https://pypi.python.org/simple/honcho/); unknown archive format: .html
    Skipping link http://docs.python.org/library/select.html (from https://pypi.python.org/simple/honcho/); unknown archive format: .html
    Skipping link http://en.wikipedia.org/wiki/Linux_Standard_Base (from https://pypi.python.org/simple/honcho/); not a file
    Skipping link http://travis-ci.org/nickstenning/honcho (from https://pypi.python.org/simple/honcho/); not a file
    Skipping link http://www.12factor.net/config (from https://pypi.python.org/simple/honcho/); not a file
    Skipping link http://www.pip-installer.org/en/latest/index.html (from https://pypi.python.org/simple/honcho/); unknown archive format: .html
    Skipping link https://devcenter.heroku.com/articles/procfile (from https://pypi.python.org/simple/honcho/); not a file
  Ignoring link https://pypi.python.org/packages/source/h/honcho/honcho-0.0.1.tar.gz#md5=2c982b087a384a15f47626c1c5adf4c9 (from https://pypi.python.org/simple/honcho/), version 0.0.1 doesn't match ==0.6.6
  Ignoring link https://pypi.python.org/packages/source/h/honcho/honcho-0.0.2.tar.gz#md5=c96100017a49db028ceb7cd2bc8dc175 (from https://pypi.python.org/simple/honcho/), version 0.0.2 doesn't match ==0.6.6
  Ignoring link https://pypi.python.org/packages/source/h/honcho/honcho-0.0.3.tar.gz#md5=ca6826f82e9f8ee54d27ccbc52486f95 (from https://pypi.python.org/simple/honcho/), version 0.0.3 doesn't match ==0.6.6
  Ignoring link https://pypi.python.org/packages/source/h/honcho/honcho-0.0.4.tar.gz#md5=3b4d2d7f9f315005fc70bae5844a2cd5 (from https://pypi.python.org/simple/honcho/), version 0.0.4 doesn't match ==0.6.6
  Ignoring link https://pypi.python.org/packages/source/h/honcho/honcho-0.1.0.tar.gz#md5=2b08188daa30f7a065ed3709f8fd76a3 (from https://pypi.python.org/simple/honcho/), version 0.1.0 doesn't match ==0.6.6
  Ignoring link https://pypi.python.org/packages/source/h/honcho/honcho-0.2.0.tar.gz#md5=3e81add102bf61f239945be655b678ec (from https://pypi.python.org/simple/honcho/), version 0.2.0 doesn't match ==0.6.6
  Ignoring link https://pypi.python.org/packages/source/h/honcho/honcho-0.3.1.tar.gz#md5=16c55160a4ce8c1e194392caf1b053fa (from https://pypi.python.org/simple/honcho/), version 0.3.1 doesn't match ==0.6.6
  Ignoring link https://pypi.python.org/packages/source/h/honcho/honcho-0.4.0.tar.gz#md5=8a9ea3aeacc7351d19fe948beb6e9737 (from https://pypi.python.org/simple/honcho/), version 0.4.0 doesn't match ==0.6.6
  Ignoring link https://pypi.python.org/packages/source/h/honcho/honcho-0.4.1.tar.gz#md5=9007734c3ba5c7d3b3eda4b28329c58c (from https://pypi.python.org/simple/honcho/), version 0.4.1 doesn't match ==0.6.6
  Ignoring link https://pypi.python.org/packages/source/h/honcho/honcho-0.4.2.tar.gz#md5=16d8269c975c38621feba75645c1f85d (from https://pypi.python.org/simple/honcho/), version 0.4.2 doesn't match ==0.6.6
  Ignoring link https://pypi.python.org/packages/source/h/honcho/honcho-0.5.0.tar.gz#md5=b93651497472baf86c4ddf84bec1467b (from https://pypi.python.org/simple/honcho/), version 0.5.0 doesn't match ==0.6.6
  Could not find a version that satisfies the requirement honcho==0.6.6 (from versions: )

No distributions matching the version for honcho==0.6.6

Exception information:
Traceback (most recent call last):
  File "/home/otree/asset-experiment-otree/env/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/home/otree/asset-experiment-otree/env/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/otree/asset-experiment-otree/env/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 978, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/home/otree/asset-experiment-otree/env/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/index.py", line 186, in find_requirement
    raise DistributionNotFound('No distributions matching the version for %s' % req)
DistributionNotFound: No distributions matching the version for honcho==0.6.6
```

Seems to me the issue is that it doesn't know this new [wheels format](http://pythonwheels.com/)...

Rasmus

`Python 2.7.3`

**Comment by oTree-org** [comment]
Haven't seen any reports of this recently...closing.
