### ISSUE TITLE
"otree startapp" shouldn't load the Django project settings

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#388]
It's not necessary for `otree startapp` to load Django before executing; this command should be like `django-admin startapp` rather than `python manage.py startapp`.

For example, one user had a problem where they added an app `public_goods_2` to their `SESSION_CONFIGS` (which automatically adds it to `INSTALLED_APPS`), and then ran `otree startapp public_goods_2`. This resulted in a confusing error:

```
Traceback (most recent call last):
  File "C:\oTree\library\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv, script_file=__file__)
  File "c:\otree\core\otree\management\cli.py", line 83, in execute_from_command_line
    django.core.management.execute_from_command_line(sys.argv)
  File "C:\oTree\venv\lib\site-packages\django\core\management\__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "C:\oTree\venv\lib\site-packages\django\core\management\__init__.py", line 312, in execute
    django.setup()
  File "C:\oTree\venv\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\oTree\venv\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\oTree\venv\lib\site-packages\django\apps\config.py", line 86, in create
    module = import_module(entry)
  File "C:\Python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named public_goods_2
```

This is because the app was part of `INSTALLED_APPS`, but at the moment the command was run, the app did not exist yet. If the user then did `otree help` to figure out what went wrong, that would result in the same error.

Maybe in `otree_cli` [here](https://github.com/oTree-org/otree-core/blob/master/otree/management/cli.py#L86) we could check if the command is `startapp` or `help`, and if so, execute it before loading Django.

**Comment by leliel12** [comment]
Now `otree_cli()` remove all the installed app before run with any of this parameters "version", "--version", "startapp", "help"
