### ISSUE TITLE
Template syntax check fails with non-ASCII characters

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#408]
Repro steps:

- intentionally modify a template to add a syntax error
- put a non-ASCII character near the syntax error
- run the checks

For example, here oTree correctly flags an illegal space after the label kwarg (should be label="e", not label = "e"):

```
C:\oTree\library [debug +2 ~2 -0 !]> otree runserver
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x0000000004D0EF98>
Traceback (most recent call last):
  File "C:\oTree\venv\lib\site-packages\django\utils\autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "C:\oTree\venv\lib\site-packages\django\core\management\commands\runserver.py", line 114, in inner_run
    self.validate(display_num_errors=True)
  File "C:\oTree\venv\lib\site-packages\django\core\management\base.py", line 469, in validate
    return self.check(app_configs=app_configs, display_num_errors=display_num_errors)
  File "C:\oTree\venv\lib\site-packages\django\core\management\base.py", line 528, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
public_goods: (otree.E008) Template syntax error in C:\oTree\library\public_goods\templates\public_goods\Contribute.html


   5 |     Contribute
   6 | {% endblock %}
   7 |
   8 | {% block content %}
   9 |
  10 |     {% formfield player.contribution with label = "e" %}
-----------^
  11 |
  12 |     {% next_button %}
  13 |
  14 |     {% include 'public_goods/Instructions.html' %}
  15 |

Error: 'with' in formfield tag needs at least one keyword argument.
```

However, if I change the e to 好 (`{% formfield player.contribution with label = "好" %}`), it chokes:

```
C:\oTree\library [debug +2 ~2 -0 !]> otree runserver
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x0000000004E5EF98>
Traceback (most recent call last):
  File "C:\oTree\venv\lib\site-packages\django\utils\autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "C:\oTree\venv\lib\site-packages\django\core\management\commands\runserver.py", line 114, in inner_run
    self.validate(display_num_errors=True)
  File "C:\oTree\venv\lib\site-packages\django\core\management\base.py", line 469, in validate
    return self.check(app_configs=app_configs, display_num_errors=display_num_errors)
  File "C:\oTree\venv\lib\site-packages\django\core\management\base.py", line 482, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\oTree\venv\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "c:\otree\core\otree\checks\__init__.py", line 252, in wrapper
    func(rules, **kwargs)
  File "c:\otree\core\otree\checks\__init__.py", line 365, in templates_have_valid_syntax
    rules.template_has_valid_syntax(template_name)
  File "c:\otree\core\otree\checks\__init__.py", line 54, in wrapper
    res = meth(self, *args, **kwargs)
  File "c:\otree\core\otree\checks\__init__.py", line 148, in template_has_valid_syntax
    arrow_position=position[0])
  File "c:\otree\core\otree\checks\templates.py", line 161, in format_source_snippet
    [format_error_line(line) for line in before],
  File "c:\otree\core\otree\checks\templates.py", line 99, in format_error_line
    return '{line.lineno:4d} | {line.source}'.format(line=line)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u597d' in position 63: ordinal not in range(128)
```

**Comment by gregmuellegger** [comment]
Fix is in `master`.
