### ISSUE TITLE
Template syntax check fails if DEBUG=False

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#409]
It seems the `django_template_source` attribute on the exception is only present in DEBUG mode?

```
C:\oTree\library [debug +2 ~1 -0 !]> otree resetdb
Traceback (most recent call last):
  File "C:\oTree\library\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv, script_file=__file__)
  File "c:\otree\core\otree\management\cli.py", line 145, in execute_from_command_line
    utility.execute()
  File "C:\oTree\venv\lib\site-packages\django\core\management\__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\oTree\venv\lib\site-packages\django\core\management\base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\oTree\venv\lib\site-packages\raven\contrib\django\management\__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "C:\oTree\venv\lib\site-packages\django\core\management\base.py", line 444, in execute
    self.check()
  File "C:\oTree\venv\lib\site-packages\django\core\management\base.py", line 482, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\oTree\venv\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "c:\otree\core\otree\checks\__init__.py", line 252, in wrapper
    func(rules, **kwargs)
  File "c:\otree\core\otree\checks\__init__.py", line 365, in templates_have_valid_syntax
    rules.template_has_valid_syntax(template_name)
  File "c:\otree\core\otree\checks\__init__.py", line 54, in wrapper
    res = meth(self, *args, **kwargs)
  File "c:\otree\core\otree\checks\__init__.py", line 145, in template_has_valid_syntax
    template_source, position = error.django_template_source
AttributeError: 'TemplateSyntaxError' object has no attribute 'django_template_source'
```

**Comment by gregmuellegger** [comment]
Fix is in `master`.
