### ISSUE TITLE
Launcher: file path UnicodeDecodeError

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#414]
A user got this error during installation with the launcher:

```
Traceback (most recent call last):
  File "C:\Users\Minha\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\pip\basecommand.py", line 232, in main
    status = self.run(options, args)
  File "C:\Users\Minha\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\pip\commands\install.py", line 339, in run
    requirement_set.prepare_files(finder)
  File "C:\Users\Minha\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\pip\req\req_set.py", line 235, in prepare_files
    req_to_install, self.upgrade)
  File "C:\Users\Minha\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\pip\index.py", line 305, in find_requirement
    page = self._get_page(main_index_url, req)
  File "C:\Users\Minha\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\pip\index.py", line 783, in _get_page
    return HTMLPage.get_page(link, req, session=self.session)
  File "C:\Users\Minha\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\pip\index.py", line 872, in get_page
    "Cache-Control": "max-age=600",
  File "C:\Users\Minha\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\pip\_vendor\requests\sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Minha\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\pip\download.py", line 365, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "C:\Users\Minha\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\pip\_vendor\requests\sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Minha\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\pip\_vendor\requests\sessions.py", line 610, in send
    r.content
  File "C:\Users\Minha\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\pip\_vendor\requests\models.py", line 730, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "C:\Users\Minha\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\pip\_vendor\requests\models.py", line 655, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\Minha\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\pip\_vendor\requests\packages\urllib3\response.py", line 256, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\Minha\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\pip\_vendor\requests\packages\urllib3\response.py", line 186, in read
    data = self._fp.read(amt)
  File "C:\Users\Minha\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 54, in read
    self.__callback(self.__buf.getvalue())
  File "C:\Users\Minha\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\pip\_vendor\cachecontrol\controller.py", line 217, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "C:\Users\Minha\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\pip\download.py", line 268, in set
    return super(SafeFileCache, self).set(*args, **kwargs)
  File "C:\Users\Minha\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\pip\_vendor\cachecontrol\caches\file_cache.py", line 83, in set
    with FileLock(name) as lock:
  File "C:\Users\Minha\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\pip\_vendor\lockfile\mkdirlockfile.py", line 18, in __init__
    LockBase.__init__(self, path, threaded, timeout)
  File "C:\Users\Minha\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\pip\_vendor\lockfile\__init__.py", line 189, in __init__
    hash(self.path)))
  File "C:\Users\Minha\AppData\Roaming\OTREE-~1\oTree\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc7 in position 0: ordinal not in range(128)
```

**Comment by oTree-org** [comment]
This looks like a related problem:

![captura de pantalla 2015-11-22 12 50 01 1](https://cloud.githubusercontent.com/assets/5423929/11660121/f4ee9a8e-9e0e-11e5-9458-4f749b4167c0.png)

**Comment by leliel12** [comment]
i currently working on it

**Comment by leliel12** [comment]
notes: http://stackoverflow.com/questions/2004137/unicodeencodeerror-on-joining-file-name

**Comment by leliel12** [comment]
i fixed this error on linux i use the bug414 branch

**Comment by leliel12** [comment]
fixed here https://github.com/oTree-org/otree-launcher/commit/250c0a226d7287b4775c032bed952b2fb22187f9
