### ISSUE TITLE
ImportError: No module named django

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#418]
Weird error..."No module named django" even though earlier in the stack trace we have `django.setup()` which means Django was already imported successfully. Also, user can do "import django" in Python shell.

```
Traceback (most recent call last):
  File "C:\Users\henny\OneDrive\Documents\oTree\projects\empty\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv, script_file=__file__)
  File "C:\Users\henny\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\otree\management\cli.py", line 145, in execute_from_command_line
    utility.execute()
  File "C:\Users\henny\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\django\core\management\__init__.py", line 328, in execute
    django.setup()
  File "C:\Users\henny\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\henny\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\henny\AppData\Roaming\OTREE-~1\oTree\lib\site-packages\django\apps\config.py", line 119, in create
    import_module(entry)
  File "C:\Python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named django
```

Launcher logs here: http://pastebin.com/raw/Cg8hWY3E

**Comment by oTree-org** [comment]
This error occurs for me also, whether using launcher or regular install in a fresh virtualenv.

**Comment by oTree-org** [comment]
I isolated the problem to kombu==0.3.32. Then found this:

https://github.com/celery/kombu/issues/553
