### ISSUE TITLE
Launcher: OSError: Command [...] setuptools pip wheel failed with error code 1

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#423]
I just downloaded the latest launcher and got this error:

```
PS C:\Users\Christopher\Downloads\otree-launcher-master (6)\otree-launcher-master> python otree.py
git version 1.9.5.msysgit.0
Cleaning older than 7 days from dir 'C:\Users\CHRIST~1\AppData\Roaming\OTREE-~1\logs'
Cleaning temp dir 'C:\Users\CHRIST~1\AppData\Roaming\OTREE-~1\temp'
Opening log file 'C:\Users\CHRIST~1\AppData\Roaming\OTREE-~1\logs\2016-01-07.log'...
Traceback (most recent call last):
  File "otree.py", line 28, in <module>
    main()
  File "otree.py", line 24, in main
    run()
  File "C:\Users\Christopher\Downloads\otree-launcher-master (6)\otree-launcher-master\otree_launcher\gui.py", line 881,
 in run
    frame.check_launcher_enviroment()
  File "C:\Users\Christopher\Downloads\otree-launcher-master (6)\otree-launcher-master\otree_launcher\gui.py", line 486,
 in check_launcher_enviroment
    self.proc = core.create_virtualenv()
  File "C:\Users\Christopher\Downloads\otree-launcher-master (6)\otree-launcher-master\otree_launcher\core.py", line 168
, in create_virtualenv
    virtualenv.create_environment(cons.LAUNCHER_VENV_PATH)
  File "C:\Users\Christopher\Downloads\otree-launcher-master (6)\otree-launcher-master\otree_launcher\libs\virtualenv\vi
rtualenv.py", line 1004, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "C:\Users\Christopher\Downloads\otree-launcher-master (6)\otree-launcher-master\otree_launcher\libs\virtualenv\vi
rtualenv.py", line 969, in install_wheel
    'PIP_NO_INDEX': '1'
  File "C:\Users\Christopher\Downloads\otree-launcher-master (6)\otree-launcher-master\otree_launcher\libs\virtualenv\vi
rtualenv.py", line 910, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command C:\Users\CHRIST~1\Ap...e\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1
```

**Comment by oTree-org** [comment]
Postponing this, to focus on other issues.
