### ISSUE TITLE
Py3: currency's __repr__() raises an exception

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#444]
```
C:\oTree\library [debug +3 ~3 -0 !]> otree shell
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from otree.common import Currency as c
>>> c(1)
Traceback (most recent call last):
  File "c:\otree\venv3\lib\site-packages\django\core\management\commands\shell.py", line 69, in handle
    self.run_shell(shell=options['interface'])
  File "c:\otree\venv3\lib\site-packages\django\core\management\commands\shell.py", line 61, in run_shell
    raise ImportError
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: __repr__ returned non-string (type bytes)
>>>
```

Looks like a bug in django-easymoney; I logged an issue here: See: https://github.com/Suor/django-easymoney/issues/4

But if someone can submit a pull request or fix it locally in otree-core that would be great, because it is causing apps like "principal agent" to crash on Py3.

**Comment by gregmuellegger** [comment]
I added a PR for the easymoney ticket: https://github.com/Suor/django-easymoney/pull/6

However this will always return a name like `Money($3.14)`. You need to keep the `__repr__` method if you want it to read `Currency(...)` instead of `Money(...)`.

**Comment by oTree-org** [comment]
Ok that's fine...

**Comment by oTree-org** [comment]
Fixed upstream
