### ISSUE TITLE
Inconsistent lenght of session._anonymous_code

### ISSUE THREAD

**Issue by Toub** [oTree-org/otree-core#453]
session.anonymous_code is declared as length=10 in otree/models/session.py, but with max-length=8 in migrations/0001_initial.py

It causes the following error with mysql:

```
Exception in thread b81e8c5603b740078bb0977289216be4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/mysql/connector/django/base.py", line 177, in _execute_wrapper
    return method(query, args)
  File "/usr/local/lib/python3.5/site-packages/mysql/connector/cursor.py", line 515, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/local/lib/python3.5/site-packages/mysql/connector/connection.py", line 488, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/local/lib/python3.5/site-packages/mysql/connector/connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.DataError: 1406 (22001): Data too long for column '_anonymous_code' at row 1

```

We have to fix it in session.py, or create a new patch for database schema.

**Comment by oTree-org** [comment]
Fixed in https://github.com/oTree-org/otree-core/commit/e53699a48f64492cc38b76691e30f5f99fdfed58
