### ISSUE TITLE
resetdb drop_tables: ProgrammingError: table "FOO_subsession" does not exist	

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#457]
I have gotten 6-7 reports of the same error from users:

On otree-core==0.4.49:

```
Traceback (most recent call last):

  File "raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "otree/management/commands/resetdb.py", line 116, in handle
    self._drop_tables(tables, db, dt_stmt)
  File "otree/management/commands/resetdb.py", line 102, in _drop_tables
    cursor.execute(stmt)
  File "django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
	
ProgrammingError: table "public_goods_2_subsession" does not exist	
```

On otree-core==0.4.34:

> I'm having trouble on Heroku when I run "heroku run otree resetdb". Group_C is the game, which is one of a few. If I clear the Heroku app, then run "heroku run otree resetdb", everything works fine. However, if I run the command without clearing the app, I get the following error in terminal. The database does show that Group_C_subsession was being created, so I'm not sure where the error arises. Any ideas where to start?

```
Traceback (most recent call last):
  File "/app/.heroku/python/bin/otree", line 9, in <module>
    load_entry_point('otree-core==0.4.34', 'console_scripts', 'otree')()
  File "/app/.heroku/python/lib/python2.7/site-packages/otree/management/cli.py", line 214, in otree_cli
    execute_from_command_line(argv, 'otree')
  File "/app/.heroku/python/lib/python2.7/site-packages/otree/management/cli.py", line 170, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python2.7/site-packages/otree/management/commands/resetdb.py", line 113, in handle
    self._drop_tables(tables, db, dt_stmt)
  File "/app/.heroku/python/lib/python2.7/site-packages/otree/management/commands/resetdb.py", line 99, in _drop_tables
    cursor.execute(stmt)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: table "group_c_subsession" does not exist
```

```
The output of heroku run otree resetdb is:
Traceback (most recent call last):
  File "/app/.heroku/python/bin/otree", line 9, in <module>
    load_entry_point('otree-core==0.4.33', 'console_scripts', 'otree')()
  File "/app/.heroku/python/lib/python2.7/site-packages/otree/management/cli.py", line 214, in otree_cli
    execute_from_command_line(argv, 'otree')
  File "/app/.heroku/python/lib/python2.7/site-packages/otree/management/cli.py", line 170, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python2.7/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python2.7/site-packages/otree/management/commands/resetdb.py", line 113, in handle
    self._drop_tables(tables, db, dt_stmt)
  File "/app/.heroku/python/lib/python2.7/site-packages/otree/management/commands/resetdb.py", line 99, in _drop_tables
    cursor.execute(stmt)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: table "survey_for_hsm_subsession" does not exist
```

**Comment by oTree-org** [comment]
case sensitivity issue...fixed in https://github.com/oTree-org/otree-core/commit/2e1ef7bc4801b4ba657555760aa7c1cdcd3992a3#diff-69e4f5cc11430187802e8717be8b39e2
