### ISSUE TITLE
resetdb drop_tables: syntax error

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#458]
Reported by user oTree mailing list. User is on Postgres.

```
Resetting the DB will destroy all current data.
Do you wish to proceed? [yN] y
[INFO|2016-04-26 13:03:51,991] otree > Selecting DROP TABLE Statement for the engine...
[INFO|2016-04-26 13:03:51,991] otree > Retrieving Existing Tables...
[INFO|2016-04-26 13:03:52,153] otree > Dropping Tables...
Traceback (most recent call last):
  File "/home3/axel/python/bin/otree", line 11, in <module>
    sys.exit(otree_cli())
  File "/home3/axel/python/lib/python2.7/site-packages/otree/management/cli.py", line 221, in otree_cli
    execute_from_command_line(argv, 'otree')
  File "/home3/axel/python/lib/python2.7/site-packages/otree/management/cli.py", line 177, in execute_from_command_line
    utility.execute()
  File "/home3/axel/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home3/axel/python/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home3/axel/python/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home3/axel/python/lib/python2.7/site-packages/otree/management/commands/resetdb.py", line 116, in handle
    self._drop_tables(tables, db, dt_stmt)
  File "/home3/axel/python/lib/python2.7/site-packages/otree/management/commands/resetdb.py", line 102, in _drop_tables
    cursor.execute(stmt)
  File "/home3/axel/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home3/axel/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home3/axel/python/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home3/axel/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: syntax error at or near "Table"
LINE 1: DROP TABLE Table 1 CASCADE;
                   ^
```

**Comment by oTree-org** [comment]
Closing unless we can repro this again. i made a fix (putting the table name in quotes) that may fix this.
