### ISSUE TITLE
Redis on Heroku: ConnectionError: max number of clients reached 

### ISSUE THREAD

**Issue by oTree-org** [oTree-org/otree-core#460]
To reproduce this bug, first ask me for access to my Heroku app running the latest version of otree-core.

Then, click the demo for "common value auction", go to the "monitor" tab, and click "advance slowest participants".

In the logs you will see errors like this:

```
May 17 00:36:25 dry-cliffs-2236 app/celeryworker.1:    File "/app/.heroku/python/lib/python3.5/site-packages/celery/backends/redis.py", line 161, in set 
May 17 00:36:25 dry-cliffs-2236 app/celeryworker.1:    File "/app/.heroku/python/lib/python3.5/site-packages/celery/backends/redis.py", line 150, in ensure 
May 17 00:36:25 dry-cliffs-2236 app/celeryworker.1:    File "/app/.heroku/python/lib/python3.5/site-packages/celery/backends/redis.py", line 170, in _set 
May 17 00:36:25 dry-cliffs-2236 app/celeryworker.1:    File "/app/.heroku/python/lib/python3.5/site-packages/redis/client.py", line 2641, in execute 
May 17 00:36:25 dry-cliffs-2236 app/celeryworker.1:    File "/app/.heroku/python/lib/python3.5/site-packages/redis/client.py", line 2495, in _execute_transaction 
May 17 00:36:25 dry-cliffs-2236 app/celeryworker.1:    File "/app/.heroku/python/lib/python3.5/site-packages/redis/connection.py", line 538, in send_packed_command 
May 17 00:36:25 dry-cliffs-2236 app/celeryworker.1:    File "/app/.heroku/python/lib/python3.5/site-packages/redis/connection.py", line 446, in connect 
May 17 00:36:25 dry-cliffs-2236 app/celeryworker.1:    File "/app/.heroku/python/lib/python3.5/site-packages/redis/connection.py", line 514, in on_connect 
May 17 00:36:25 dry-cliffs-2236 app/celeryworker.1:    File "/app/.heroku/python/lib/python3.5/site-packages/redis/connection.py", line 577, in read_response 
May 17 00:36:25 dry-cliffs-2236 app/celeryworker.1:    File "/app/.heroku/python/lib/python3.5/site-packages/redis/connection.py", line 255, in read_response 
May 17 00:36:25 dry-cliffs-2236 app/celeryworker.1:  redis.exceptions.ConnectionError: max number of clients reached 
May 17 00:37:04 dry-cliffs-2236 app/worker.1:  15:37:04 worker5 |   File "/app/.heroku/python/lib/python3.5/site-packages/redis/client.py", line 2626, in execute 
May 17 00:37:04 dry-cliffs-2236 app/worker.1:  15:37:04 worker5 |   File "/app/.heroku/python/lib/python3.5/site-packages/redis/client.py", line 2495, in _execute_transaction 
May 17 00:37:04 dry-cliffs-2236 app/worker.1:  15:37:04 worker5 |   File "/app/.heroku/python/lib/python3.5/site-packages/redis/connection.py", line 538, in send_packed_command 
May 17 00:37:04 dry-cliffs-2236 app/worker.1:  15:37:04 worker5 |   File "/app/.heroku/python/lib/python3.5/site-packages/redis/connection.py", line 446, in connect 
May 17 00:37:04 dry-cliffs-2236 app/worker.1:  15:37:04 worker5 |   File "/app/.heroku/python/lib/python3.5/site-packages/redis/connection.py", line 514, in on_connect 
May 17 00:37:04 dry-cliffs-2236 app/worker.1:  15:37:04 worker5 |   File "/app/.heroku/python/lib/python3.5/site-packages/redis/connection.py", line 577, in read_response 
May 17 00:37:04 dry-cliffs-2236 app/worker.1:  15:37:04 worker5 |   File "/app/.heroku/python/lib/python3.5/site-packages/redis/connection.py", line 255, in read_response 
May 17 00:37:04 dry-cliffs-2236 app/worker.1:  15:37:04 worker5 | redis.exceptions.ConnectionError: max number of clients reached 
May 17 00:37:04 dry-cliffs-2236 app/worker.1:  15:37:04 worker5 |   File "/app/.heroku/python/lib/python3.5/site-packages/kombu/transport/redis.py", line 690, in _size 
May 17 00:37:04 dry-cliffs-2236 app/worker.1:  15:37:04 worker5 |   File "/app/.heroku/python/lib/python3.5/site-packages/redis/client.py", line 2641, in execute 
May 17 00:37:04 dry-cliffs-2236 app/worker.1:  15:37:04 worker5 |   File "/app/.heroku/python/lib/python3.5/site-packages/redis/client.py", line 2495, in _execute_transaction 
May 17 00:37:04 dry-cliffs-2236 app/worker.1:  15:37:04 worker5 |   File "/app/.heroku/python/lib/python3.5/site-packages/redis/connection.py", line 538, in send_packed_command 
May 17 00:37:04 dry-cliffs-2236 app/worker.1:  15:37:04 worker5 |   File "/app/.heroku/python/lib/python3.5/site-packages/redis/connection.py", line 446, in connect 
May 17 00:37:04 dry-cliffs-2236 app/worker.1:  15:37:04 worker5 |   File "/app/.heroku/python/lib/python3.5/site-packages/redis/connection.py", line 514, in on_connect 
May 17 00:37:04 dry-cliffs-2236 app/worker.1:  15:37:04 worker5 |   File "/app/.heroku/python/lib/python3.5/site-packages/redis/connection.py", line 577, in read_response 
May 17 00:37:04 dry-cliffs-2236 app/worker.1:  15:37:04 worker5 |   File "/app/.heroku/python/lib/python3.5/site-packages/redis/connection.py", line 255, in read_response 
May 17 00:37:04 dry-cliffs-2236 app/worker.1:  15:37:04 worker5 | redis.exceptions.ConnectionError: max number of clients reached 
```

It works fine for me locally.

This happens even if I use the Heroku Redis Premium plan that allows 40 connections: https://elements.heroku.com/addons/heroku-redis

I am wondering if we can fix this by configuring Redis+celery differently. Or if there is a bug in otree-core code with how it connects to Redis.

otree-core uses Redis for 3 things:

(1) Django channels backend (for WebSockets/async)
(2) Celery transport
(3) Celery result backend

When I just have the channels worker (1) running there is no error, even when I downgrade to the free Redis add-on that only allows 20 redis connections. It's when I turn on the celery dyno that the Max connections are reached. So I think the problem is either (2) or (3).

I tried configuring by setting `CELERY_REDIS_MAX_CONNECTIONS=2` and `BROKER_POOL_LIMIT=3` but that didn't work.

The task here is to figure out where these extra connections come from, either by inspecting otree-core source code or monitoring the connections to redis somehow.

**Comment by weilu** [comment]
I'm seeing this again on otree 2.5.8:


```
2020-07-11T01:23:21.836543+00:00 app[web.1]: 01:23:21 asgiserver | Traceback (most recent call last):
2020-07-11T01:23:21.836701+00:00 app[web.1]: 01:23:21 asgiserver |   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
2020-07-11T01:23:21.836853+00:00 app[web.1]: 01:23:21 asgiserver |     response = get_response(request)
2020-07-11T01:23:21.837006+00:00 app[web.1]: 01:23:21 asgiserver |   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
2020-07-11T01:23:21.837155+00:00 app[web.1]: 01:23:21 asgiserver |     response = self.process_exception_by_middleware(e, request)
2020-07-11T01:23:21.837307+00:00 app[web.1]: 01:23:21 asgiserver |   File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
2020-07-11T01:23:21.837459+00:00 app[web.1]: 01:23:21 asgiserver |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2020-07-11T01:23:21.837607+00:00 app[web.1]: 01:23:21 asgiserver |   File "/app/.heroku/python/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
2020-07-11T01:23:21.837753+00:00 app[web.1]: 01:23:21 asgiserver |     return self.dispatch(request, *args, **kwargs)
2020-07-11T01:23:21.837899+00:00 app[web.1]: 01:23:21 asgiserver |   File "/app/.heroku/python/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
2020-07-11T01:23:21.838043+00:00 app[web.1]: 01:23:21 asgiserver |     return bound_method(*args, **kwargs)
2020-07-11T01:23:21.838186+00:00 app[web.1]: 01:23:21 asgiserver |   File "/app/.heroku/python/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
2020-07-11T01:23:21.838328+00:00 app[web.1]: 01:23:21 asgiserver |     return view_func(*args, **kwargs)
2020-07-11T01:23:21.838472+00:00 app[web.1]: 01:23:21 asgiserver |   File "/app/.heroku/python/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
2020-07-11T01:23:21.838613+00:00 app[web.1]: 01:23:21 asgiserver |     return bound_method(*args, **kwargs)
2020-07-11T01:23:21.838761+00:00 app[web.1]: 01:23:21 asgiserver |   File "/app/.heroku/python/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
2020-07-11T01:23:21.838947+00:00 app[web.1]: 01:23:21 asgiserver |     response = view_func(request, *args, **kwargs)
2020-07-11T01:23:21.839090+00:00 app[web.1]: 01:23:21 asgiserver |   File "/app/.heroku/python/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
2020-07-11T01:23:21.839232+00:00 app[web.1]: 01:23:21 asgiserver |     return bound_method(*args, **kwargs)
2020-07-11T01:23:21.839375+00:00 app[web.1]: 01:23:21 asgiserver |   File "/app/.heroku/python/lib/python3.7/site-packages/django/views/decorators/cache.py", line 31, in _cache_controlled
2020-07-11T01:23:21.839515+00:00 app[web.1]: 01:23:21 asgiserver |     response = viewfunc(request, *args, **kw)
2020-07-11T01:23:21.839657+00:00 app[web.1]: 01:23:21 asgiserver |   File "/app/.heroku/python/lib/python3.7/site-packages/otree/views/abstract.py", line 280, in dispatch
2020-07-11T01:23:21.839798+00:00 app[web.1]: 01:23:21 asgiserver |     with lock, otree.db.idmap.use_cache():
2020-07-11T01:23:21.839945+00:00 app[web.1]: 01:23:21 asgiserver |   File "/app/.heroku/python/lib/python3.7/site-packages/redis_lock/__init__.py", line 342, in __enter__
2020-07-11T01:23:21.840084+00:00 app[web.1]: 01:23:21 asgiserver |     acquired = self.acquire(blocking=True)
2020-07-11T01:23:21.840231+00:00 app[web.1]: 01:23:21 asgiserver |   File "/app/.heroku/python/lib/python3.7/site-packages/redis_lock/__init__.py", line 231, in acquire
2020-07-11T01:23:21.840380+00:00 app[web.1]: 01:23:21 asgiserver |     if self._held:
2020-07-11T01:23:21.840516+00:00 app[web.1]: 01:23:21 asgiserver |   File "/app/.heroku/python/lib/python3.7/site-packages/redis_lock/__init__.py", line 203, in _held
2020-07-11T01:23:21.840656+00:00 app[web.1]: 01:23:21 asgiserver |     return self.id == self.get_owner_id()
2020-07-11T01:23:21.840798+00:00 app[web.1]: 01:23:21 asgiserver |   File "/app/.heroku/python/lib/python3.7/site-packages/redis_lock/__init__.py", line 217, in get_owner_id
2020-07-11T01:23:21.840937+00:00 app[web.1]: 01:23:21 asgiserver |     owner_id = self._client.get(self._name)
2020-07-11T01:23:21.841079+00:00 app[web.1]: 01:23:21 asgiserver |   File "/app/.heroku/python/lib/python3.7/site-packages/redis/client.py", line 1332, in get
2020-07-11T01:23:21.841230+00:00 app[web.1]: 01:23:21 asgiserver |     return self.execute_command('GET', name)
2020-07-11T01:23:21.841371+00:00 app[web.1]: 01:23:21 asgiserver |   File "/app/.heroku/python/lib/python3.7/site-packages/redis/client.py", line 836, in execute_command
2020-07-11T01:23:21.841515+00:00 app[web.1]: 01:23:21 asgiserver |     conn = self.connection or pool.get_connection(command_name, **options)
2020-07-11T01:23:21.841660+00:00 app[web.1]: 01:23:21 asgiserver |   File "/app/.heroku/python/lib/python3.7/site-packages/redis/connection.py", line 1071, in get_connection
2020-07-11T01:23:21.841825+00:00 app[web.1]: 01:23:21 asgiserver |     connection.connect()
2020-07-11T01:23:21.841966+00:00 app[web.1]: 01:23:21 asgiserver |   File "/app/.heroku/python/lib/python3.7/site-packages/redis/connection.py", line 547, in connect
2020-07-11T01:23:21.842114+00:00 app[web.1]: 01:23:21 asgiserver |     self.on_connect()
2020-07-11T01:23:21.842314+00:00 app[web.1]: 01:23:21 asgiserver |   File "/app/.heroku/python/lib/python3.7/site-packages/redis/connection.py", line 617, in on_connect
2020-07-11T01:23:21.842518+00:00 app[web.1]: 01:23:21 asgiserver |     if nativestr(self.read_response()) != 'OK':
2020-07-11T01:23:21.842691+00:00 app[web.1]: 01:23:21 asgiserver |   File "/app/.heroku/python/lib/python3.7/site-packages/redis/connection.py", line 699, in read_response
2020-07-11T01:23:21.842857+00:00 app[web.1]: 01:23:21 asgiserver |     response = self._parser.read_response()
2020-07-11T01:23:21.842977+00:00 app[web.1]: 01:23:21 asgiserver |   File "/app/.heroku/python/lib/python3.7/site-packages/redis/connection.py", line 470, in read_response
2020-07-11T01:23:21.843096+00:00 app[web.1]: 01:23:21 asgiserver |     raise response
2020-07-11T01:23:21.843223+00:00 app[web.1]: 01:23:21 asgiserver | redis.exceptions.ConnectionError: max number of clients reached
```
