### ISSUE TITLE
500 in PayMTurk with Python 3.5

### ISSUE THREAD

**Issue by paulgirard** [oTree-org/otree-core#473]
I am using Otree 0.5 with python 3.5 on my own server Cent OS 7, daphne, redis, nginx (reverse proxy).

When I submitted the HITs to Mturk I experienced a series of 500 errors with the same stack trace (see below).

This happens when I selected the 13 assignments of one session then clicked on pay and confirmed.
From my 8 sessions, The bug appeared something like 5 times.
When it occurs going back to the session admin page shows that some of the assignments were confirmed some not.
Reselecting the pending assignments and clicking the pay button again worked.

I also tried to select less than 13 assignments and experienced the same issue with less.

It looked like a synchronisation problem with the API (about HITS state approved/submited) calls but honestly I didn't make a proper inquiry about the issue.

Here is one of the stack trace
```bash
Internal Server Error: /PayMTurk/20/
Traceback (most recent call last):
  File "/store/venvs-python3.5/otree-prod/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/store/venvs-python3.5/otree-prod/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/store/venvs-python3.5/otree-prod/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/store/venvs-python3.5/otree-prod/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/store/venvs-python3.5/otree-prod/lib/python3.5/site-packages/otree/views/mturk.py", line 311, in post
    mturk_connection.approve_assignment(p.mturk_assignment_id)
  File "/store/venvs-python3.5/otree-prod/lib/python3.5/site-packages/boto/mturk/connection.py", line 425, in approve_assignment
    return self._process_request('ApproveAssignment', params)
  File "/store/venvs-python3.5/otree-prod/lib/python3.5/site-packages/boto/mturk/connection.py", line 838, in _process_request
    return self._process_response(response, marker_elems)
  File "/store/venvs-python3.5/otree-prod/lib/python3.5/site-packages/boto/mturk/connection.py", line 853, in _process_response
    raise MTurkRequestError(response.status, response.reason, body)
boto.mturk.connection.MTurkRequestError: MTurkRequestError: 200 OK
<?xml version="1.0" encoding="UTF-8"?>
<ApproveAssignmentResponse>
   <OperationRequest>
      <RequestId>ff432685-8613-48bf-a427-763409bf9e14</RequestId>
   </OperationRequest>
   <ApproveAssignmentResult>
      <Request>
         <IsValid>False</IsValid>
         <Errors>
            <Error>
               <Code>AWS.MechanicalTurk.InvalidAssignmentState</Code>
               <Message>This operation can be called with a status of: Submitted (1465052796412)</Message>
               <Data>
                  <Key>ExpectedStates</Key>
                  <Value>Submitted</Value>
               </Data>
               <Data>
                  <Key>CurrentState</Key>
                  <Value>Approved</Value>
               </Data>
               <Data>
                  <Key>ExpectedStates</Key>
                  <Value>Submitted</Value>
               </Data>
            </Error>
         </Errors>
      </Request>
   </ApproveAssignmentResult>
</ApproveAssignmentResponse>
`

**Comment by oTree-org** [comment]
I put a safeguard against this in a code so we display a message rather than crashing. But I can't repro it myself. Try updating to today's release and let me know if it happens again. And if you have repro steps, let me know.

**Comment by paulgirard** [comment]
Ok writting to log is a good workaround for now.
We don't plan new experiments on Mturk in close future so we might not provide more precise repro steps.
In any case, I let you know.
