### ISSUE TITLE
Model inheritance doesn't seem to work

### ISSUE THREAD

**Issue by qwiglydee** [oTree-org/otree-core#554]
I want to separate code into modules/classes.
Neither inheritance nor mixin approach works.

Version A:
```python
class MyBasePlayer(api.BasePlayer):
    __abstract__ = True
    foo = models.IntegerField(initial=0)

class Player(MyBasePlayer):
    bar = models.IntegerField(initial=0)
```

Version B:
```python
class MyBasePlayer():
    foo = models.IntegerField(initial=0)

class Player(MyBasePlayer, api.BasePlayer):
    bar = models.IntegerField(initial=0)
```

Both fail:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 747, in __getattr__
    return getattr(self.comparator, key)
AttributeError: 'Comparator' object has no attribute 'form_props'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/otree", line 8, in <module>
    sys.exit(execute_from_command_line())
  File "/usr/local/lib/python3.8/site-packages/otree/main.py", line 106, in execute_from_command_line
    setup()
  File "/usr/local/lib/python3.8/site-packages/otree/main.py", line 140, in setup
    init_orm()
  File "/usr/local/lib/python3.8/site-packages/otree/database.py", line 278, in init_orm
    elif field.form_props.get('choices'):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 749, in __getattr__
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
AttributeError: Neither 'OTreeColumn' object nor 'Comparator' object has an attribute 'form_props'
```

**Comment by oTree-org** [comment]
This kind of inheritance is not supported, sorry.

**Comment by oTree-org** [comment]
(By the way, even if you did get it working, I don't recommend using SQLAlchemy features and other internal aspects of oTree because they are not part of oTree's stable API.)

**Comment by qwiglydee** [comment]
That's a shame.
Modular code has really many advantages.
