### ISSUE TITLE
TypeError: get_context_data() got an unexpected keyword argument 'form'

### ISSUE THREAD

**Issue by qwiglydee** [oTree-org/otree-core#555]
The error happens when using bots to test some bogus page sequence. 
Conditions are not yet known, but they are related to misplaced WaitPages with restricted visibility
(implementing workflow "a player with role S waits players with roles A and B")

However the "unexpected keyword" seems like a compatibility issue (perhaps, messing with old/new code).

```
Traceback (most recent call last):
  File "/usr/local/bin/otree", line 8, in <module>
    sys.exit(execute_from_command_line())
  File "/usr/local/lib/python3.8/site-packages/otree/main.py", line 113, in execute_from_command_line
    call_command(cmd, *argv[2:])
  File "/usr/local/lib/python3.8/site-packages/otree/cli/base.py", line 28, in call_command
    module.Command().outer_handle(args)
  File "/usr/local/lib/python3.8/site-packages/otree/cli/base.py", line 9, in outer_handle
    return self.handle(**vars(options))
  File "/usr/local/lib/python3.8/site-packages/otree/cli/bots.py", line 54, in handle
    run_all_bots_for_session_config(
  File "/usr/local/lib/python3.8/site-packages/otree/bots/runner.py", line 159, in run_all_bots_for_session_config
    run_bots(session_id, case_number=case_number)
  File "/usr/local/lib/python3.8/site-packages/otree/bots/runner.py", line 124, in run_bots
    runner.play()
  File "/usr/local/lib/python3.8/site-packages/otree/bots/runner.py", line 53, in play
    bot.submit(submission)
  File "/usr/local/lib/python3.8/site-packages/otree/bots/bot.py", line 369, in submit
    self.response = self.client.post(self.url, post_data, allow_redirects=True)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/starlette/testclient.py", line 413, in request
    return super().request(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/starlette/testclient.py", line 243, in send
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/testclient.py", line 240, in send
    loop.run_until_complete(self.app(scope, receive, send))
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 26, in __call__
    await response(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 224, in __call__
    await run_until_first_complete(
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 24, in run_until_first_complete
    [task.result() for task in done]
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 24, in <listcomp>
    [task.result() for task in done]
  File "/usr/local/lib/python3.8/site-packages/starlette/responses.py", line 216, in stream_response
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 56, in body_stream
    task.result()
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/otree/errorpage.py", line 247, in __call__
    raise exc  # from None
  File "/usr/local/lib/python3.8/site-packages/otree/errorpage.py", line 227, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/usr/local/lib/python3.8/site-packages/otree/middleware.py", line 42, in dispatch
    response = await call_next(request)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/sessions.py", line 75, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/usr/local/lib/python3.8/site-packages/otree/patch.py", line 41, in __call__
    raise exc  # from None
  File "/usr/local/lib/python3.8/site-packages/otree/patch.py", line 29, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 582, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 243, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/otree/views/abstract.py", line 109, in dispatch
    response = await run_in_threadpool(self.inner_dispatch, request)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/otree/views/abstract.py", line 401, in inner_dispatch
    return self.get()
  File "/usr/local/lib/python3.8/site-packages/otree/views/abstract.py", line 464, in get
    context = self.get_context_data(form=form)
TypeError: get_context_data() got an unexpected keyword argument 'form'
```

**Comment by qwiglydee** [comment]
Sorry. My bad. 

I accidentally put both `api.Page` an `api.WaitPage` into bases.
