### ISSUE TITLE
otree devserver fails to set return value

### ISSUE THREAD

**Issue by peterjc** [oTree-org/otree-core#565]
Problem identified on macOS, using Python 3.8.5 installed via conda:

```
$ otree --version
5.2.8
$ python --version
Python 3.8.5
```

**Steps to reproduce:**

1. Take a working oTree example, and change to its directory
2. Insert ``assert False`` as the first line of ``Settings.py`` to break the example
3. Run a production server and check the return value is non-zero:

```
$ otree prodserver ; echo $?
Traceback (most recent call last):
  File "/Users/xxx/opt/miniconda3/bin/otree", line 8, in <module>
    sys.exit(execute_from_command_line())
  File "/Users/xxx/opt/miniconda3/lib/python3.8/site-packages/otree/main.py", line 106, in execute_from_command_line
    setup()
  File "/Users/xxx/opt/miniconda3/lib/python3.8/site-packages/otree/main.py", line 133, in setup
    from otree import settings
  File "/Users/xxx/opt/miniconda3/lib/python3.8/site-packages/otree/settings.py", line 30, in <module>
    import settings
  File "/xxx/settings.py", line 1, in <module>
    assert False
AssertionError
1
```

Good, the example failed and there was a non-zero return value of 1.

4. Run a development server and check the return value is non-zero:

```
$ otree devserver ; echo $?
Traceback (most recent call last):
  File "/Users/xxx/opt/miniconda3/bin/otree", line 8, in <module>
    sys.exit(execute_from_command_line())
  File "/Users/xxx/opt/miniconda3/lib/python3.8/site-packages/otree/main.py", line 106, in execute_from_command_line
    setup()
  File "/Users/xxx/opt/miniconda3/lib/python3.8/site-packages/otree/main.py", line 133, in setup
    from otree import settings
  File "/Users/xxx/opt/miniconda3/lib/python3.8/site-packages/otree/settings.py", line 30, in <module>
    import settings
  File "/xxx/settings.py", line 1, in <module>
    assert False
AssertionError
0
```

Bad, despite failing there was a return value of 0.

**Observed behaviour:**

Despite failing, ``otree devserver`` gave a return value of zero indicating no error.

**Expected behaviour:**

If it fails, ``otree devserver`` should return non-zero indicating an error.

**Comment by peterjc** [comment]
Part of the problem could be no explicit return value at all, in ``setup.py`` you have:

```python
entry_points={'console_scripts': ['otree=otree.main:execute_from_command_line']},
```

And that does:

```python
def execute_from_command_line(*args, **kwargs):
    ...
    from otree.cli.base import call_command

    call_command(cmd, *argv[2:])
```

i.e. In the main case there is an implicit ``return None`` and thus the overall return value will probably be controlled by the error handling?
