### ISSUE TITLE
'Submission' object has no attribute '__name__'

### ISSUE THREAD

**Issue by somas95** [oTree-org/otree-core#575]
When writing bots, `yield Submission(...)` produces the following error:

```
Traceback (most recent call last):
  File ".../venv/bin/otree", line 33, in <module>
    sys.exit(load_entry_point('otree==5.9.3', 'console_scripts', 'otree')())
  File ".../venv/lib64/python3.9/site-packages/otree/main.py", line 110, in execute_from_command_line
    call_command(cmd, *argv[2:])
  File ".../venv/lib64/python3.9/site-packages/otree/cli/base.py", line 32, in call_command
    module.Command().outer_handle(args)
  File ".../venv/lib64/python3.9/site-packages/otree/cli/base.py", line 10, in outer_handle
    return self.handle(**vars(options))
  File ".../venv/lib64/python3.9/site-packages/otree/cli/bots.py", line 54, in handle
    run_all_bots_for_session_config(
  File ".../venv/lib64/python3.9/site-packages/otree/bots/runner.py", line 158, in run_all_bots_for_session_config
    run_bots(session_id, case_number=case_number)
  File ".../venv/lib64/python3.9/site-packages/otree/bots/runner.py", line 125, in run_bots
    runner.play()
  File ".../venv/lib64/python3.9/site-packages/otree/bots/runner.py", line 48, in play
    submission = bot.get_next_submit()
  File ".../venv/lib64/python3.9/site-packages/otree/bots/bot.py", line 234, in get_next_submit
    return next(self.submits_generator)
  File ".../venv/lib64/python3.9/site-packages/otree/bots/bot.py", line 244, in get_submits
    submission = BareYieldToSubmission(submission)
  File ".../venv/lib64/python3.9/site-packages/otree/bots/bot.py", line 460, in BareYieldToSubmission
    return Submission(PageClass, post_data)
  File ".../venv/lib64/python3.9/site-packages/otree/bots/bot.py", line 114, in __init__
    self.page_class_dotted: str = get_dotted_name(PageClass)
  File ".../venv/lib64/python3.9/site-packages/otree/common.py", line 106, in get_dotted_name
    return '{}.{}'.format(Cls.__module__, Cls.__name__)
AttributeError: 'Submission' object has no attribute '__name__'
```

**Comment by oTree-org** [comment]
It works fine for me. Can you show me code to reproduce this? Maybe you have a page called Submission that shadows the otree.api.Submission? etc

**Comment by somas95** [comment]
The  tests code looks like

```python
import random
from otree.api import Currency as c, currency_range, expect, Bot
from . import *

def call_live_method(method, **kwargs):
    for i in range(100):
        method(1,{'type': 'answer',
                  'answer': random.choice(['secure', 'risky'])})
        method(1, {'type': 'next'})

class PlayerBot(Bot):
    def play_round(self):
        yield BlockChange,
        yield Submission(BlockPages, {}, check_html=False),
        yield GameResults
```

BlockPages is a live page, but I tried commenting it and yielding a Submission(BlockChange) with the same result.

There's no Submission page. I'm using python3.9 and oTree (5.9.3)

**Comment by oTree-org** [comment]
Can you reproduce this with a new app? Like this:
```
from otree.api import *


doc = """
Your app description
"""


class C(BaseConstants):
    NAME_IN_URL = 'bot_submission'
    PLAYERS_PER_GROUP = None
    NUM_ROUNDS = 1


class Subsession(BaseSubsession):
    pass


class Group(BaseGroup):
    pass


class Player(BasePlayer):
    pass


# PAGES
class MyPage(Page):
    pass


class ResultsWaitPage(WaitPage):
    pass


class Results(Page):
    pass


page_sequence = [MyPage, Results]

```


```
from otree.api import *
from . import *


class PlayerBot(Bot):
    def play_round(self):
        # compete price
        yield Submission(MyPage)
```

**Comment by somas95** [comment]
I cannot reproduce it in a new app. I wonder what is happening
